/** Słowa kluczowe scoringu przetargów — synchronizuj z supabase/functions/.../index.tsx (BZP_*). */

/** Czynność: remont, wykończenie, malowanie, wymiana podłóg… */
export const TENDER_ACTION_KEYWORDS = [
  "remont",
  "moderniz",
  "termomoderniz",
  "wykończ",
  "wykończen",
  "przebudow",
  "renowac",
  "adaptacj",
  "rehabilit",
  "odśwież",
  "termo",
  "konserwac",
  "napraw",
  "odnow",
  "wymian",
  "podłącz",
  "podlacz",
  "demonta",
  "monta",
  "układ",
  "ukladan",
  "malow",
  "tapet",
  "tapetow",
  "tynk",
  "gładź",
  "gladz",
  "szpachl",
  "glazur",
  "płytek",
  "plytek",
  "fugow",
  "posadzk",
  "podłog",
  "podlog",
  "sufit",
  "parkiet",
  "wykładzin",
  "wykladzin",
  "regips",
  "zabudow",
  "cyklin",
  "lakier",
  "olejow",
  "okładzin",
  "okladzin",
  "sztukator",
  "impregnat",
  "natrysk",
  "szlif",
] as const;

/** Zakres: obiekty (hale, uniwerki, lokale…) + elementy (pomieszczenia, ściany, podłogi…). */
export const TENDER_SCOPE_KEYWORDS = [
  // pomieszczenia i elementy
  "pomieszcze",
  "pomieszczen",
  "wnętrz",
  "wnetrz",
  "lokal ",
  "lokalu",
  "lokali",
  "lokale",
  "mieszkan",
  "apartament",
  "segment",
  "pustostan",
  "korytarz",
  "hol ",
  "holu",
  "przedpok",
  "garderob",
  "spiżarn",
  "spizarn",
  "sala ",
  "sal ",
  "aula",
  "auli",
  "ścian",
  "scian",
  "sufit",
  "posadzk",
  "podłog",
  "podlog",
  "tynk",
  "malow",
  "tapeta",
  "glazura",
  "płytk",
  "plytk",
  "okładzin",
  "okladzin",
  "parapet",
  "cokół",
  "cokol",
  "balustrad",
  "barierk",
  "poręcz",
  "porecz",
  "klatk",
  "schodisk",
  "schod",
  "piętr",
  "pietr",
  "parter",
  "piwnic",
  "strych",
  "toalet",
  "sanitar",
  "łazienk",
  "lazienk",
  "kuchni",
  "garaż",
  "garaz",
  // budynki i typy obiektów
  "budynk",
  "biur",
  "biurow",
  "biurowc",
  "administracyj",
  "hala ",
  "hali ",
  "hale ",
  "magazyn",
  "fabryk",
  "hali produkcy",
  "warsztat",
  "pracowni",
  "laboratori",
  "uniwersytet",
  "uczelni",
  "collegium",
  "wydział",
  "wydzial",
  "instytut",
  "akademi",
  "dydaktyczn",
  "akademik",
  "domu studenck",
  "dom studenck",
  "internat",
  "szpital",
  "przychodni",
  "gabinet",
  "poradni",
  "klinik",
  "szkoł",
  "przedszk",
  "żłobek",
  "zlobek",
  "bibliotek",
  "muzeum",
  "centrum kultury",
  "dom kultury",
  "dom kultur",
  "świetlic",
  "swietlic",
  "stołówk",
  "stolowk",
  "jadalni",
  "basen",
  "hala sport",
  "obiekt sport",
  "siłowni",
  "silowni",
  "rekreacji",
  "hotel",
  "hostel",
  "pensjonat",
  "nocleg",
  "urząd",
  "urzedu",
  "sąd",
  "sad ",
  "prokurat",
  "komendy",
  "remiz",
  "straż poż",
  "straz poz",
  "poczta",
  "poczty",
  "kościoł",
  "kosciol",
  "kaplic",
  "filia",
  "oddział",
  "oddzial",
  "dom opieki",
  "pieczy zastępc",
  "pieczy zastepc",
  "kamienic",
  "osiedl",
  "blok ",
  "wspólnot",
  "wspolnot",
  "centrum handlow",
  "galeria handl",
  "sklep",
  "kiosk",
  "pawilon",
  "lokale usług",
  "lokali uslug",
  "lokale handl",
  "lokali handl",
  "lokale użytk",
  "lokale uzytk",
  "usługow",
  "uslugow",
  "handlow",
  "nieruchomo",
  "obiekt budowl",
  // stolarka, elewacja, instalacje
  "elewac",
  "dach",
  "stolark",
  "okien",
  "okno",
  "drzwi",
  "wind",
  "dźwig",
  "dzwig",
  "izolac",
  "instalac",
  "elektrycz",
  "oświetl",
  "osietlen",
  "okablow",
  "rozdzieln",
  "tablic rozdziel",
  "przewod",
  "gniazd",
  "gniazdk",
  "opraw oświet",
  "opraw osiet",
  "zasilani",
  "uziemien",
  "niskoprąd",
  "niskopradow",
  "teletechnik",
  "domofon",
  "videofon",
  "sap ",
  "system alarm",
  "pogotowie energet",
  "grzewcz",
  "wentylac",
  "klimatyzac",
  "wodno-kanal",
  "wodno kanal",
  "wod-kan",
  "hydraulic",
  "sanitarn",
  "co ",
  "centralnego ogrzew",
] as const;

/** Wykluczenia: drogi, sieci, nowa zabudowa, infrastruktura liniowa. */
export const TENDER_EXCLUDE_KEYWORDS = [
  "drogi wojewódzk",
  "nawierzchni jezdni",
  "chodników drogow",
  "przebudowa drogi",
  "remont drogi",
  "remont dróg",
  "remont nawierzchni",
  "rozbudowa skrzyżowania",
  "budowa drogi",
  "budowa dróg",
  "nawierzchni bitum",
  "utwardzenie placu drogowego",
  "kanalizacji deszczowej",
  "wodociąg",
  "gazociąg",
  "most ",
  "wiadukt",
  "prom ",
  "linii kolejow",
  "budowa budynk",
  "budowa obiektu",
  "budowa nowego",
  "budowa hali magazyn",
  "budowa budynku",
  "wykonanie obiektu budowl",
  "roboty budowlane polegające na budowie",
  "roboty ziemne",
  "wycinka drzew",
  "boisko sportowe",
  "nawierzchni sportowej",
] as const;

/** Luźniejsze hinty dla kluczowych zamawiających Wrocławia (gdy brak słowa „remont” w tytule). */
export const TENDER_PRIORITY_BUILDING_HINTS = [
  ...TENDER_ACTION_KEYWORDS,
  ...TENDER_SCOPE_KEYWORDS,
] as readonly string[];

const RENOVATION_SIGNALS = [
  "remont", "moderniz", "przebudow", "termomoderniz", "adaptacj", "rozbudow", "renowac",
  "wykończ", "wykończen", "wymian", "malow", "odnow",
];

/** „Budowa” bez sygnału remontu/modernizacji = nowa zabudowa — odrzucamy. */
export function isNewConstructionTitle(title: string): boolean {
  const t = title.toLowerCase();
  if (!t.includes("budowa")) return false;
  return !RENOVATION_SIGNALS.some((s) => t.includes(s));
}

export function matchTenderKeywords(
  title: string,
  custom?: { action?: readonly string[]; scope?: readonly string[] },
): {
  actionKeywords: string[];
  scopeKeywords: string[];
  allKeywords: string[];
} {
  const t = title.toLowerCase();
  const actionSrc = custom?.action?.length ? custom.action : TENDER_ACTION_KEYWORDS;
  const scopeSrc = custom?.scope?.length ? custom.scope : TENDER_SCOPE_KEYWORDS;
  const actionKeywords = actionSrc.filter((kw) => t.includes(kw));
  const scopeKeywords = scopeSrc.filter((kw) => t.includes(kw));
  return { actionKeywords, scopeKeywords, allKeywords: [...actionKeywords, ...scopeKeywords] };
}

export function hasRenovationSignal(
  title: string,
  custom?: { action?: readonly string[]; scope?: readonly string[] },
): boolean {
  const { actionKeywords, scopeKeywords } = matchTenderKeywords(title, custom);
  if (actionKeywords.length > 0) return true;
  if (scopeKeywords.length >= 2) return true;
  return false;
}

export function isExcludedTenderTitle(
  title: string,
  customExclude?: readonly string[],
): boolean {
  const t = title.toLowerCase();
  const ex = customExclude?.length ? customExclude : TENDER_EXCLUDE_KEYWORDS;
  if (ex.some((e) => t.includes(e))) return true;
  return isNewConstructionTitle(t);
}
