/**
 * AI-DOC-DETECTION — Thin DF (alias + UX copy + Doc.D1/D2/D3).
 * DF: AI-DOC-DETECTION-THIN-DESIGN-FREEZE-01
 */

export {
  DOC_DETECTION_ALIAS_VERSION,
  DOC_DETECTION_COPY_VERSION,
  DOC_LAYER_LABEL_PL,
  DOC_D2_INVESTOR_COST_LABEL_PL,
  type DocDetectionLayer,
} from "./types";

export {
  foldDocDetectionFilename,
  matchesDocD1NewAlias,
  hasDocD1CostFilenameHint,
  isDocD1PdfFilename,
  DOC_D1_PDF_NAME_RE,
} from "./aliases";

export {
  type DocDetectionUxCause,
  DOC_DETECTION_UX_A_LABEL,
  DOC_DETECTION_UX_A_HINT,
  DOC_DETECTION_UX_B_LABEL,
  DOC_DETECTION_UX_B_HINT,
  DOC_DETECTION_UX_C_CANDIDATE_LABEL,
  DOC_DETECTION_UX_C_CANDIDATE_HINT,
  DOC_DETECTION_UX_C_ARCHIVE_READY_LABEL,
  DOC_DETECTION_UX_C_ARCHIVE_READY_HINT,
  DOC_DETECTION_UX_C_RUNNING_LABEL,
  DOC_DETECTION_UX_C_RUNNING_HINT,
  DOC_DETECTION_UX_C_FAILED_LABEL,
  DOC_DETECTION_UX_C_FAILED_HINT,
  DOC_DETECTION_UX_C_ZIP_NOT_FOUND_LABEL,
  DOC_DETECTION_UX_C_ZIP_NOT_FOUND_HINT,
  DOC_DETECTION_UX_C_ZIP_PARSE_FAILED_LABEL,
  DOC_DETECTION_UX_C_ZIP_PARSE_FAILED_HINT,
  DOC_DETECTION_UX_D_LABEL,
  DOC_DETECTION_UX_D_HINT,
  DOC_DETECTION_UX_F1_LABEL,
  DOC_DETECTION_UX_F1_HINT,
} from "./copy";

export {
  mapDossierKosztorysPresentation,
  type DossierDocPresentation,
  type CostStatusForDocPresentation,
} from "./dossier-presentation";
